name = "ngapak-tim"
main = "src/index.js"
compatibility_date = "2025-05-01"

[vars]
DOMAINS = "miuzy.web.id"
# ADMIN_KEY = "admin"
# SUPABASE_URL = "https://dzvdymslbthecxjdtgag.supabase.co"
# SUPABASE_KEY = "sb_publishable_peZXT6Kq_WguHZaqjT1TzQ_8HD6eymD"
